version: '3.8'

networks:
  chnet:
    driver: bridge

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    restart: unless-stopped
    networks:
      - chnet
    ports:
      - "8500:8500"
    command: "consul agent -dev -client=0.0.0.0"


  host3_20240618:
    image: mysql:8.0
    container_name: host3_20240618
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: tooo
      MYSQL_DATABASE: game
    volumes:
      - /Users/alberto/Downloads/tech-interview-challenge/backups/host3_fulldump_20240618_212019.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
    ports:
      - "3307:3306"
    networks:
      - chnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
    depends_on:
      - consul
    entrypoint: >
      sh -c "while ! curl -s http://consul:8500/v1/status/leader; do echo waiting for consul; sleep 3; done &&
             echo 'registering in consul' &&
             curl -X PUT --data '{\"ID\": \"host3_20240618\", \"Name\": \"mysql\", \"Address\": \"host3_20240618\", \"Port\": 3306}' http://consul:8500/v1/agent/service/register &&
             docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"

  host2_20240618:
    image: mysql:8.0
    container_name: host2_20240618
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: tooo
      MYSQL_DATABASE: game
    volumes:
      - /Users/alberto/Downloads/tech-interview-challenge/backups/host2_fulldump_20240618_211855.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
    ports:
      - "3308:3306"
    networks:
      - chnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
    depends_on:
      - consul
    entrypoint: >
      sh -c "while ! curl -s http://consul:8500/v1/status/leader; do echo waiting for consul; sleep 3; done &&
             echo 'registering in consul' &&
             curl -X PUT --data '{\"ID\": \"host2_20240618\", \"Name\": \"mysql\", \"Address\": \"host2_20240618\", \"Port\": 3306}' http://consul:8500/v1/agent/service/register &&
             docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"

  host1_20240618:
    image: mysql:8.0
    container_name: host1_20240618
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: tooo
      MYSQL_DATABASE: game
    volumes:
      - /Users/alberto/Downloads/tech-interview-challenge/backups/host1_fulldump_20240618_211508.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
    ports:
      - "3309:3306"
    networks:
      - chnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
    depends_on:
      - consul
    entrypoint: >
      sh -c "while ! curl -s http://consul:8500/v1/status/leader; do echo waiting for consul; sleep 3; done &&
             echo 'registering in consul' &&
             curl -X PUT --data '{\"ID\": \"host1_20240618\", \"Name\": \"mysql\", \"Address\": \"host1_20240618\", \"Port\": 3306}' http://consul:8500/v1/agent/service/register &&
             docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"


  elixir_api:
    restart: unless-stopped
    build:
      context: ./db_query_api
    ports:
      - "4000:4000"
    environment:
      CONSUL_HTTP_ADDR: "http://consul:8500"
      MYSQL_ROOT_PASSWORD: "tooo"
    depends_on:
      - consul

      - host3_20240618

      - host2_20240618

      - host1_20240618

    networks:
      - chnet